### ISSUE TITLE
Is it me or is it broken?

### ISSUE THREAD

**Issue by dagnelies** [taginfo/taginfo#397]
Almost all pages are "blank", missing all data.

![image](https://user-images.githubusercontent.com/5452653/225277558-f8e74bbd-23f0-4d0d-9ed2-71e72c799a71.png)

If I remember correctly, it was all working just fine a couple of weeks ago.

**Comment by dagnelies** [comment]
Might be related to the recent commits:

- https://github.com/taginfo/taginfo/commit/85586edfbbe94f2554859393823d2297b9e261d5 
- https://github.com/taginfo/taginfo/commit/0166dd23e23082cf382434f77fa967cacf9b831e

Since the browser console shows:

       Uncaught ReferenceError: build_link_with_prefix is not defined
        at build_link (tags:14:31)
        at page_init (tags.js:3:14)
        at HTMLDocument.<anonymous> (taginfo.js:858:9)
        at j (common.js:2:27244)
        at Object.fireWith [as resolveWith] (common.js:2:28057)
        at Function.ready (common.js:2:29891)
        at HTMLDocument.J (common.js:2:30257)

**Comment by dagnelies** [comment]
Turns out to be a caching issue. The browser probably still loaded the "old" scripts that were cached.
